// actionTypes.js

export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL';

export const LOAD_SELLER_REQUEST = 'LOAD_SELLER_REQUEST';
export const LOAD_SELLER_SUCCESS = 'LOAD_SELLER_SUCCESS';
export const LOAD_SELLER_FAIL = 'LOAD_SELLER_FAIL';

export const UPDATE_USER_INFO_REQUEST = 'UPDATE_USER_INFO_REQUEST';
export const UPDATE_USER_INFO_SUCCESS = 'UPDATE_USER_INFO_SUCCESS';
export const UPDATE_USER_INFO_FAIL = 'UPDATE_USER_INFO_FAIL';

export const UPDATE_USER_ADDRESS_REQUEST = 'UPDATE_USER_ADDRESS_REQUEST';
export const UPDATE_USER_ADDRESS_SUCCESS = 'UPDATE_USER_ADDRESS_SUCCESS';
export const UPDATE_USER_ADDRESS_FAIL = 'UPDATE_USER_ADDRESS_FAIL';

export const DELETE_USER_ADDRESS_REQUEST = 'DELETE_USER_ADDRESS_REQUEST';
export const DELETE_USER_ADDRESS_SUCCESS = 'DELETE_USER_ADDRESS_SUCCESS';
export const DELETE_USER_ADDRESS_FAIL = 'DELETE_USER_ADDRESS_FAIL';

export const GET_ALL_USERS_REQUEST = 'GET_ALL_USERS_REQUEST';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAIL = 'GET_ALL_USERS_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';

export const GET_ALL_SELLERS_REQUEST = 'GET_ALL_SELLERS_REQUEST';
export const GET_ALL_SELLERS_SUCCESS = 'GET_ALL_SELLERS_SUCCESS';
export const GET_ALL_SELLERS_FAIL = 'GET_ALL_SELLERS_FAIL';

export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST';
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS';
export const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL';

export const GET_ALL_PRODUCTS_SHOP_REQUEST = 'GET_ALL_PRODUCTS_SHOP_REQUEST';
export const GET_ALL_PRODUCTS_SHOP_SUCCESS = 'GET_ALL_PRODUCTS_SHOP_SUCCESS';
export const GET_ALL_PRODUCTS_SHOP_FAILED = 'GET_ALL_PRODUCTS_SHOP_FAILED';

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAILED = 'DELETE_PRODUCT_FAILED';

export const GET_ALL_PRODUCTS_REQUEST = 'GET_ALL_PRODUCTS_REQUEST';
export const GET_ALL_PRODUCTS_SUCCESS = 'GET_ALL_PRODUCTS_SUCCESS';
export const GET_ALL_PRODUCTS_FAILED = 'GET_ALL_PRODUCTS_FAILED';

export const EVENT_CREATE_REQUEST = 'EVENT_CREATE_REQUEST';
export const EVENT_CREATE_SUCCESS = 'EVENT_CREATE_SUCCESS';
export const EVENT_CREATE_FAIL = 'EVENT_CREATE_FAIL';
export const GET_ALL_EVENTS_SHOP_REQUEST = 'GET_ALL_EVENTS_SHOP_REQUEST';
export const GET_ALL_EVENTS_SHOP_SUCCESS = 'GET_ALL_EVENTS_SHOP_SUCCESS';
export const GET_ALL_EVENTS_SHOP_FAIL = 'GET_ALL_EVENTS_SHOP_FAIL';
export const DELETE_EVENT_REQUEST = 'DELETE_EVENT_REQUEST';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';
export const DELETE_EVENT_FAIL = 'DELETE_EVENT_FAIL';
export const GET_ALL_EVENTS_REQUEST = 'GET_ALL_EVENTS_REQUEST';
export const GET_ALL_EVENTS_SUCCESS = 'GET_ALL_EVENTS_SUCCESS';
export const GET_ALL_EVENTS_FAIL = 'GET_ALL_EVENTS_FAIL';

export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';

export const GET_ALL_ORDERS_USER_REQUEST = 'getAllOrdersUserRequest';
export const GET_ALL_ORDERS_USER_SUCCESS = 'getAllOrdersUserSuccess';
export const GET_ALL_ORDERS_USER_FAILED = 'getAllOrdersUserFailed';

export const GET_ALL_ORDERS_SHOP_REQUEST = 'getAllOrdersShopRequest';
export const GET_ALL_ORDERS_SHOP_SUCCESS = 'getAllOrdersShopSuccess';
export const GET_ALL_ORDERS_SHOP_FAILED = 'getAllOrdersShopFailed';

export const ADMIN_ALL_ORDERS_REQUEST = 'adminAllOrdersRequest';
export const ADMIN_ALL_ORDERS_SUCCESS = 'adminAllOrdersSuccess';
export const ADMIN_ALL_ORDERS_FAILED = 'adminAllOrdersFailed';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
